AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create an Auto Scaling Group for Chatwoot instances'

Parameters:
  KeyPairName:
    Description: 'Name of an existing EC2 KeyPair to enable SSH access to the instances'
    Type: 'AWS::EC2::KeyPair::KeyName'

  ChatwootAMI:
    Description: 'AMI ID for the Chatwoot instance'
    Type: 'AWS::EC2::Image::Id'

Resources:
  SumoChatwootLaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateData:
        ImageId: !Ref ChatwootAMI
        InstanceType: c5.xlarge
        KeyName: !Ref KeyPairName
        NetworkInterfaces:
          - AssociatePublicIpAddress: false
            DeviceIndex: 0
            SubnetId: !ImportValue  SumoChatwootProdStack-SumoChatwootPublicSubnet1Id
            Groups:
              - !ImportValue SumoChatwootProdStack-SumoChatwootLoadBalancerSGId
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 60  # GB
              VolumeType: gp2
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: sumo-chatwoot-instance-template-prod

  # Auto Scaling Group
  SumoChatwootAutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier: 
        - !ImportValue  SumoChatwootProdStack-SumoChatwootPublicSubnet1Id
        - !ImportValue  SumoChatwootProdStack-SumoChatwootPublicSubnet2Id
      LaunchTemplate:
        LaunchTemplateId: !Ref SumoChatwootLaunchTemplate
        Version: !GetAtt SumoChatwootLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      DesiredCapacity: '1'
      MaxSize: '4'
      TargetGroupARNs:
        - !ImportValue SumoChatwootProdStack-SumoChatwootTargetGroupArn
      Tags:
        - Key: Name
          Value: sumo-chatwoot-auto-scaling-group-prod
          PropagateAtLaunch: true
      Cooldown: 300 # Default cooldown period for the Auto Scaling Group in seconds

  # Scaling Policy
  SumoChatwootScalingPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AutoScalingGroupName: !Ref SumoChatwootAutoScalingGroup
      PolicyName: 'CPUScalingPolicy'
      PolicyType: 'TargetTrackingScaling'
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: 'ASGAverageCPUUtilization'
        TargetValue: 50.0  # Adjust target CPU utilization as needed
      EstimatedInstanceWarmup: 300 # Optional: Time in seconds that instances take to become ready to handle traffic
      Cooldown: 300 # Cooldown in the scaling policy if needed (overrides the ASG cooldown)

Outputs:
  AutoScalingGroupName:
    Description: 'The name of the Auto Scaling Group'
    Value: !Ref SumoChatwootAutoScalingGroup

