AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create a Route 53 hosted zone and an A record'

Parameters:
  HostedZoneId:
    Description: 'The ID of the existing Route 53 hosted zone'
    Type: 'AWS::Route53::HostedZone::Id'

  DomainName:
    Description: 'The fully qualified domain name for the DNS record (e.g., chat.sumoscheduler.com)'
    Type: 'String'
    Default: 'chat.sumoscheduler.com'

Resources:
  # Create an A Record in the Hosted Zone
  SumoChatwootDNSRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: 'A'
      # TTL: '60'  # Set TTL to 60 seconds
      # ResourceRecords: 
      #   - !ImportValue SumoChatwootStack-SumoChatwootInstanceIP
      AliasTarget: 
        DNSName: !ImportValue SumoChatwootStack-SumoChatwootLoadBalancerDNSName
        HostedZoneId: !ImportValue SumoChatwootStack-SumoChatwootLoadBalancerCanonicalHostedZoneId

Outputs:
  DevRecordSetName:
    Description: 'The name of the DNS record set created'
    Value: !Ref DomainName

