### Create account
POST https://dev-chat.sumoscheduler.com/platform/api/v1/accounts
api_access_token: x28UHUJKGxREdccnorpJbMLU
Content-Type: application/json

{
  "name": "Test1"
}

### Create user
POST https://dev-chat.sumoscheduler.com/platform/api/v1/users
api_access_token: x28UHUJKGxREdccnorpJbMLU
Content-Type: application/json

{
  "name": "Test user1",
  "email": "mytestemail@email.com",
  "password": "someStrongRandomPassword1#"
}

### Link user to account
POST https://dev-chat.sumoscheduler.com/platform/api/v1/accounts/2/account_users
api_access_token: x28UHUJKGxREdccnorpJbMLU
Content-Type: application/json

{
  "user_id": 3,
  "role": "agent"
}

### Get Login url
GET https://dev-chat.sumoscheduler.com/platform/api/v1/users/3/login
api_access_token: x28UHUJKGxREdccnorpJbMLU

### Login user
GET http://localhost:3000/app/login?email=mytestemail%40email.com&sso_auth_token=b81ea7305ea5017e4438b997d3f2fcdc085eb5b4d8ab5ff7050c3cfc6de95e37
