AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for PostgreSQL RDS setup for Chatwoot'

Parameters:
  SumoChatwootVPCId:
    Description: 'VPC ID where the RDS instance will be deployed'
    Type: 'AWS::EC2::VPC::Id'

  SumoChatwootPrivateSubnet1Id:
    Description: 'Private Subnet 1 ID'
    Type: 'AWS::EC2::Subnet::Id'

  SumoChatwootPrivateSubnet2Id:
    Description: 'Private Subnet 2 ID'
    Type: 'AWS::EC2::Subnet::Id'

  SumoChatwootLoadBalancerSGId:
    Description: 'SumoChatwootLoadBalancerSG ID'
    Type: 'AWS::EC2::SecurityGroup::Id'

  SumoChatwootDBUsername:
    Description: 'The database admin account username'
    NoEcho: true
    Type: 'String'
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: 'must begin with a letter and contain only alphanumeric characters.'

  SumoChatwootDBPassword:
    Description: 'The database admin account password'
    NoEcho: true
    Type: 'String'
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9@]*'
    ConstraintDescription: 'must contain only alphanumeric characters and/or @.'

Resources:
  # Security Group for RDS
  SumoChatwootRDSDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref SumoChatwootVPCId
      GroupDescription: Security group for Chatwoot RDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref SumoChatwootLoadBalancerSGId
      Tags:
        - Key: Name
          Value: sumo-chatwoot-rds-sg

  # RDS Subnet Group
  SumoChatwootRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Chatwoot RDS
      SubnetIds:
        - !Ref SumoChatwootPrivateSubnet1Id
        - !Ref SumoChatwootPrivateSubnet2Id
      Tags:
        - Key: Name
          Value: sumo-chatwoot-rds-group

  # RDS Instance
  SumoChatwootRDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: sumo-chatwoot-db
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Ref SumoChatwootDBUsername
      MasterUserPassword: !Ref SumoChatwootDBPassword
      DBSubnetGroupName: !Ref SumoChatwootRDSSubnetGroup
      VPCSecurityGroups:
        - !Ref SumoChatwootRDSDBSecurityGroup
      MultiAZ: true
      PubliclyAccessible: false
      AllocatedStorage: 20
      StorageType: gp2
      Tags:
        - Key: Name
          Value: sumo-chatwoot-postgres

Outputs:
  SumoChatwootRDSInstanceEndpoint:
    Description: 'The connection endpoint for the RDS instance'
    Value: !GetAtt SumoChatwootRDSDBInstance.Endpoint.Address

  SumoChatwootRDSInstancePort:
    Description: 'The port of the RDS instance'
    Value: !GetAtt SumoChatwootRDSDBInstance.Endpoint.Port