AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for PostgreSQL RDS setup for Chatwoot'

Parameters:
  SumoChatwootDBUsername:
    Description: 'The database admin account username'
    NoEcho: true
    Type: 'String'
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: 'must begin with a letter and contain only alphanumeric characters.'

  SumoChatwootDBPassword:
    Description: 'The database admin account password'
    NoEcho: true
    Type: 'String'
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9@]*'
    ConstraintDescription: 'must contain only alphanumeric characters and/or @.'

Resources:
  # Security Group for RDS
  SumoChatwootRDSDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue SumoChatwootStack-SumoChatwootVPCId
      GroupDescription: Security group for Chatwoot RDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !ImportValue SumoChatwootStack-SumoChatwootLoadBalancerSGId
      Tags:
        - Key: Name
          Value: sumo-chatwoot-rds-sg

  # RDS Subnet Group
  SumoChatwootRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Chatwoot RDS
      SubnetIds:
        - !ImportValue SumoChatwootStack-SumoChatwootPrivateSubnet1Id
        - !ImportValue SumoChatwootStack-SumoChatwootPrivateSubnet2Id
      Tags:
        - Key: Name
          Value: sumo-chatwoot-rds-group

  # RDS Instance
  SumoChatwootProdRDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: sumo-chatwoot-prod-db
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Ref SumoChatwootDBUsername
      MasterUserPassword: !Ref SumoChatwootDBPassword
      DBSubnetGroupName: !Ref SumoChatwootRDSSubnetGroup
      VPCSecurityGroups:
        - !Ref SumoChatwootRDSDBSecurityGroup
      MultiAZ: true
      PubliclyAccessible: false
      AllocatedStorage: 20
      StorageType: gp2
      Tags:
        - Key: Name
          Value: sumo-chatwoot-prod-postgres

  SumoChatwootDevRDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: sumo-chatwoot-dev-db
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Ref SumoChatwootDBUsername
      MasterUserPassword: !Ref SumoChatwootDBPassword
      DBSubnetGroupName: !Ref SumoChatwootRDSSubnetGroup
      VPCSecurityGroups:
        - !Ref SumoChatwootRDSDBSecurityGroup
      MultiAZ: true
      PubliclyAccessible: false
      AllocatedStorage: 20
      StorageType: gp2
      Tags:
        - Key: Name
          Value: sumo-chatwoot-dev-postgres

Outputs:
  SumoChatwootProdRDSInstanceEndpoint:
    Description: 'The connection endpoint for the RDS instance'
    Value: !GetAtt SumoChatwootProdRDSDBInstance.Endpoint.Address
    Export:
      Name: SumoChatwootStack-SumoChatwootProdRDSInstanceEndpoint

  SumoChatwootProdRDSInstancePort:
    Description: 'The port of the RDS instance'
    Value: !GetAtt SumoChatwootProdRDSDBInstance.Endpoint.Port
    Export:
      Name: SumoChatwootStack-SumoChatwootProdRDSInstancePort

  SumoChatwootDevRDSInstanceEndpoint:
    Description: 'The connection endpoint for the RDS instance'
    Value: !GetAtt SumoChatwootDevRDSDBInstance.Endpoint.Address
    Export:
      Name: SumoChatwootStack-SumoChatwootDevRDSInstanceEndpoint

  SumoChatwootDevRDSInstancePort:
    Description: 'The port of the RDS instance'
    Value: !GetAtt SumoChatwootDevRDSDBInstance.Endpoint.Port
    Export:
      Name: SumoChatwootStack-SumoChatwootDevRDSInstancePort
