AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for PostgreSQL RDS setup for Chatwoot'

Parameters:
  Environment:
    Description: "Deployment environment (e.g., dev, prod)"
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev

  SumoChatwootDBUsername:
    Description: 'The database admin account username'
    NoEcho: true
    Type: 'String'
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: 'must begin with a letter and contain only alphanumeric characters.'

  SumoChatwootDBPassword:
    Description: 'The database admin account password'
    NoEcho: true
    Type: 'String'
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9@]*'
    ConstraintDescription: 'must contain only alphanumeric characters and/or @.'

Resources:
  # Security Group for RDS
  SumoChatwootRDSDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue !Sub "SumoChatwoot-${Environment}-SumoChatwootVPCId"
      GroupDescription: Security group for Chatwoot RDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !ImportValue !Sub "SumoChatwoot-${Environment}-SumoChatwootLoadBalancerSGId"
      Tags:
        - Key: Name
          Value: !Sub "sumo-chatwoot-rds-sg-${Environment}"
        - Key: Environment
          Value: !Ref Environment

  # RDS Subnet Group
  SumoChatwootRDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for Chatwoot RDS
      SubnetIds:
        - !ImportValue !Sub "SumoChatwoot-${Environment}-SumoChatwootPrivateSubnet1Id"
        - !ImportValue !Sub "SumoChatwoot-${Environment}-SumoChatwootPrivateSubnet2Id"
      Tags:
        - Key: Name
          Value: !Sub "sumo-chatwoot-rds-group-${Environment}"
        - Key: Environment
          Value: !Ref Environment

  # RDS Instance
  SumoChatwootRDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "sumo-chatwoot-db-${Environment}"
      DBInstanceClass: db.t3.micro
      Engine: postgres
      MasterUsername: !Ref SumoChatwootDBUsername
      MasterUserPassword: !Ref SumoChatwootDBPassword
      DBSubnetGroupName: !Ref SumoChatwootRDSSubnetGroup
      VPCSecurityGroups:
        - !Ref SumoChatwootRDSDBSecurityGroup
      MultiAZ: true
      PubliclyAccessible: false
      AllocatedStorage: 20
      StorageType: gp2
      Tags:
        - Key: Name
          Value: !Sub "sumo-chatwoot-postgres-${Environment}"
        - Key: Environment
          Value: !Ref Environment

Outputs:
  SumoChatwootRDSInstanceEndpoint:
    Description: 'The connection endpoint for the RDS instance'
    Value: !GetAtt SumoChatwootRDSDBInstance.Endpoint.Address
    Export:
      Name: !Sub "SumoChatwoot-${Environment}-SumoChatwootRDSInstanceEndpoint"

  SumoChatwootRDSInstancePort:
    Description: 'The port of the RDS instance'
    Value: !GetAtt SumoChatwootRDSDBInstance.Endpoint.Port
    Export:
      Name: !Sub "SumoChatwoot-${Environment}-SumoChatwootRDSInstancePort"
