AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Redis ElastiCache setup for Chatwoot'

Parameters:
  Environment:
    Description: "Deployment environment (e.g., dev, prod)"
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev
    
Resources:
  # Security Group for Redis
  SumoChatwootRedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !ImportValue "SumoChatwoot-${Environment}-SumoChatwootVPCId"
      GroupDescription: Security group for Chatwoot Redis
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !ImportValue "SumoChatwoot-${Environment}-SumoChatwootLoadBalancerSGId"
      Tags:
        - Key: Name
          Value: !Sub "sumo-chatwoot-redis-sg-${Environment}"
        - Key: Environment
          Value: !Ref Environment

  # ElastiCache Subnet Group
  SumoChatwootRedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for Chatwoot Redis
      SubnetIds:
        - !ImportValue "SumoChatwoot-${Environment}-SumoChatwootPrivateSubnet1Id"
        - !ImportValue "SumoChatwoot-${Environment}-SumoChatwootPrivateSubnet2Id"
      Tags:
        - Key: Name
          Value: !Sub "sumo-chatwoot-redis-group-${Environment}"
        - Key: Environment
          Value: !Ref Environment

  # Redis Cluster
  SumoChatwootRedisCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupDescription: Chatwoot Redis cluster
      ReplicationGroupId: !Sub "sumo-chatwoot-redis-${Environment}"
      Engine: redis
      CacheNodeType: cache.t3.micro
      NumCacheClusters: 2
      AutomaticFailoverEnabled: true
      SecurityGroupIds:
        - !Ref SumoChatwootRedisSecurityGroup
      CacheSubnetGroupName: !Ref SumoChatwootRedisSubnetGroup
      Tags:
        - Key: Name
          Value: !Sub "sumo-chatwoot-redis-${Environment}"
        - Key: Environment
          Value: !Ref Environment

Outputs:
  SumoChatwootRedisEndpointAddress:
    Description: 'Primary endpoint address for the Redis cluster'
    Value: !GetAtt SumoChatwootRedisCluster.PrimaryEndPoint.Address
    Export:
      Name: !Sub "SumoChatwoot-${Environment}-SumoChatwootRedisEndpointAddress"

  SumoChatwootRedisEndpointPort:
    Description: 'Primary endpoint port for the Redis cluster'
    Value: !GetAtt SumoChatwootRedisCluster.PrimaryEndPoint.Port
    Export:
      Name: !Sub "SumoChatwoot-${Environment}-SumoChatwootRedisEndpointPort"
