AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create a Route 53 hosted zone and an A record'

Parameters:
  Environment:
    Description: "Deployment environment (e.g., dev, prod)"
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev

  HostedZoneId:
    Description: 'The ID of the existing Route 53 hosted zone'
    Type: 'AWS::Route53::HostedZone::Id'

  DomainName:
    Description: 'The fully qualified domain name for the DNS record (e.g., chat.sumoscheduler.com)'
    Type: 'String'
    Default: 'dev-chat.sumoscheduler.com'

Resources:
  # Create an A Record in the Hosted Zone
  SumoChatwootDNSRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: 'A'
      # TTL: '60'  # Set TTL to 60 seconds
      # ResourceRecords: 
      #   - !ImportValue SumoChatwootDevStack-SumoChatwootInstanceIP
      AliasTarget: 
        DNSName: !ImportValue 
          Fn::Sub: "SumoChatwoot-${Environment}-LoadBalancerDNSName"
        HostedZoneId: !ImportValue 
          Fn::Sub: "SumoChatwoot-${Environment}-LoadBalancerCanonicalHostedZoneId"

Outputs:
  RecordSetName:
    Description: 'The name of the DNS record set created'
    Value: !Ref DomainName

