name: Backup Repository to S3

on:
  schedule:
    - cron: '0 0 * * *' # Runs every Sunday at 2 AM UTC
  workflow_dispatch: # Allows manual trigger of the workflow

  push:
    branches:
      - develop
          
jobs:
  backup:
    name: Backup Repository and Upload to S3
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Backup S3 bucket
      - name: Backup S3 bucket Cloudformation
        run: |
          aws cloudformation validate-template \
            --template-body file://aws_cloudformation/backup.yml

          STACK_NAME=sumo-chatwoot-backup
          aws cloudformation deploy \
            --template-file aws_cloudformation/backup.yml \
            --stack-name $STACK_NAME \
            --capabilities CAPABILITY_NAMED_IAM

          BackupBucketName=$(aws cloudformation describe-stacks --stack-name $STACK_NAME --query "Stacks[0].Outputs[?OutputKey=='BackupBucketName'].OutputValue" --output text)
          echo "BackupBucketName=${BackupBucketName}" >> $GITHUB_ENV
            
      # Step 4: Compress the repository into a tarball
      - name: Create repository backup using git archive
        run: |
          git archive --format=tar.gz -o sumo-chatwoot-backup.tar.gz HEAD
          # tar -czvf sumo-chatwoot-backup.tar.gz . # Compress the entire repository
          echo "Backup file created: sumo-chatwoot-backup.tar.gz"

      # Step 5: Upload the backup to S3
      - name: Upload backup to S3
        run: |
          BACKUP_NAME="repo-backup-$(date +'%Y-%m-%d_%H-%M-%S').tar.gz"
          aws s3 cp sumo-chatwoot-backup.tar.gz s3://${{ env.BackupBucketName }}/$BACKUP_NAME
          echo "Backup uploaded as $BACKUP_NAME"

      # Step 6: Retain only the last 5 backups
      - name: Clean up old backups
        run: |
          echo "Ensuring only the last 5 backups are retained..."
          BACKUPS=$(aws s3 ls s3://${{ env.BackupBucketName }}/ | sort | head -n -5 | awk '{print $4}')
          for BACKUP in $BACKUPS; do
            echo "Deleting old backup: $BACKUP"
            aws s3 rm s3://${{ env.BackupBucketName }}/$BACKUP
          done

      # Optional Step 7: List backups in S3
      - name: List backups in S3
        run: aws s3 ls s3://${{ env.BackupBucketName }}/