name: Deploy Sumo Chatwoot Infrastructure

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Creating a Key Pair Using AWS CLI
        id: retrieve-key
        run: |
          key_name="${{ secrets.KEY_NAME }}"
          PEM_FILE="$key_name.pem"
          if [ ! -f "$PEM_FILE" ]; then
            if ! aws ec2 describe-key-pairs --key-names "$key_name" 2>/dev/null; then
              aws ec2 create-key-pair --key-name "$key_name" --query 'KeyMaterial' --output text > "$PEM_FILE"
              chmod 400 "$PEM_FILE"
              echo "key_created=true" >> $GITHUB_ENV
            else
              echo "Key pair $key_name already exists, but PEM file is not available."
            fi
          fi

      - name: Upload Key Pair PEM File as Artifact
        if: env.key_created == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: key-pair-pem
          path: ${{ secrets.KEY_NAME }}.pem

      - name: Validate Cloudformation
        run: |
          aws cloudformation validate-template \
            --template-body file://aws_cloudformation/template.yml

      - name: Deploy CloudFormation Stack
        run: |
          STACK_NAME=sumo-chatwoot-stack
          aws cloudformation deploy \
            --template-file aws_cloudformation/template.yml \
            --stack-name $STACK_NAME \
            --parameter-overrides \
              SumoChatwootDBMasterUsername=${{ secrets.RDS_MASTER_USERNAME }} \
              SumoChatwootDBMasterUserPassword=${{ secrets.RDS_MASTER_PASSWORD }} \
              SumoChatwootCertificateArn=${{ secrets.ACM_CERTIFICATE_ARN }} \
              SumoChatwootKeyName=${{ secrets.KEY_NAME}} \
              GithubToken=${{ secrets.GIT_TOKEN}} \
            --capabilities CAPABILITY_NAMED_IAM

          echo "CloudFormation Outputs:"
          aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs' --output table

          InstancePublicIP=$(aws cloudformation describe-stacks \
          --stack-name $STACK_NAME \
          --query "Stacks[0].Outputs[?OutputKey=='InstancePublicIP'].OutputValue" \
          --output text)
          echo "EC2_PUBLIC_IP=${InstancePublicIP}" >> $GITHUB_ENV

          RDSInstanceEndpoint=$(aws cloudformation describe-stacks \
          --stack-name $STACK_NAME \
          --query "Stacks[0].Outputs[?OutputKey=='RDSInstanceEndpoint'].OutputValue" \
          --output text)
          echo "POSTGRES_HOST=${RDSInstanceEndpoint}" >> $GITHUB_ENV

          RedisPrimaryEndpoint=$(aws cloudformation describe-stacks \
          --stack-name $STACK_NAME \
          --query "Stacks[0].Outputs[?OutputKey=='RedisPrimaryEndpoint'].OutputValue" \
          --output text)
          echo "REDIS_HOST=${RedisPrimaryEndpoint}" >> $GITHUB_ENV

      - name: Upload Source Code to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ steps.retrieve-key.outputs.PEM_FILE }}
          source: './'
          target: '/home/ubuntu/sumo-chatwoot'
                  
      - name: Update EC2 with new source code
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ steps.retrieve-key.outputs.PEM_FILE }}
          script: |
            export POSTGRES_HOST=${{ env.POSTGRES_HOST }}
            export POSTGRES_USERNAME=${{ secrets.RDS_MASTER_USERNAME }}
            export POSTGRES_PASSWORD=${{ secrets.RDS_MASTER_PASSWORD }}
            export REDIS_HOST=${{ env.POSTGRES_HOST }}
            export RAILS_ENV='production'

            cd /home/ubuntu/sumo-chatwoot
            git pull origin develop
            chmod 777 install.sh
            sudo ./install.sh --install
            
      # - name: Retrieve CloudFormation Outputs
      #   id: cf-outputs
      #   run: |
      #     aws cloudformation describe-stacks --stack-name sumo-chatwoot-stack --query 'Stacks[0].Outputs' --output json

      - name: Print CloudFormation Outputs
        run: |
          echo "CloudFormation Outputs:"
          aws cloudformation describe-stacks --stack-name sumo-chatwoot-stack --query 'Stacks[0].Outputs' --output table

      # - name: Create the AMI
      #   run: |
      #     echo "Create the AMI"
      #     INSTANCE_ID=$(aws cloudformation describe-stacks --stack-name YourStackName --query 'Stacks[0].Outputs[?OutputKey==`ChatwootInstanceId`].OutputValue' --output text)
      #     aws ec2 create-image --instance-id $INSTANCE_ID --name "chatwoot-base-ami" --description "Base AMI for Chatwoot application" --no-reboot

      - name: Post-deployment script
        run: |
          echo "Deployment complete!"
